module.exports = {
  // database constants
  SUBSCRIPTION_STATUS: ["SUBSCRIBED", "UNSUBSCRIBED"],
  COUPON_USERS: ["NEW_USER", "EXISTING_USER", "ALL_USER"],
  DISCOUNT_TYPE: ["AMOUNT", "PERCENTAGE"],
  COUPON_STATUS: ["ACTIVE", "EXPIRED", "HOLD", "PENDING"],
};
